language: node_js
node_js:
  - "stable"
  - "iojs"

env:
  - DOCKER_HOST=tcp://127.0.0.1:2376

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run test
  - npm run coverage-ci